edition = "2021"
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true

# Unstable
comment_width = 100
empty_item_single_line = true
fn_params_layout = "Tall"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Mixed"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
unstable_features = true
wrap_comments = true
