allow = [
    # Checks for casts between numerical types that may truncate large values
    # https://rust-lang.github.io/rust-clippy/master/index.html#cast%20possible%20truncation
    "clippy::cast_possible_truncation",
    # Checks for casts from an unsigned type to a signed type of the same size
    # https://rust-lang.github.io/rust-clippy/master/index.html#cast%20possible%20wrap
    "clippy::cast_possible_wrap",
    # Checks for casts from any numerical to a float type where the receiving type cannot store
    # all values from the original type without rounding errors
    # https://rust-lang.github.io/rust-clippy/master/index.html#cast%20precision%20loss
    "clippy::cast_precision_loss",
    # Checks for casts from signed to unsigned types
    # https://rust-lang.github.io/rust-clippy/master/index.html#cast%20sign%20loss
    "clippy::cast_sign_loss",
    # Checks to see if multiple versions of a crate are being used
    # (The `proc-macro-error` crate uses an outdated version of `syn`)
    # https://rust-lang.github.io/rust-clippy/master/index.html#/multiple%20crate%20versions
    "clippy::multiple_crate_versions",
    # Checks for private functions that only return `Some` or `None`
    # (The `[`solve!`]` macro expects `Option`s)
    # https://rust-lang.github.io/rust-clippy/master/index.html#/unnecessary%20wraps
    "clippy::unnecessary_wraps"
]
warn = [
    "clippy::all",
    "clippy::cargo",
    "clippy::nursery",
    "clippy::pedantic"
]
deny = [
    "missing_docs",
    # Cranky does not yet support `forbid`
    "unsafe_code",
]
